#!/usr/bin/env bash
# SSH into web-01
ssh ubuntu@web-01

# Enable ufw
sudo ufw enable

# Set default incoming policy to deny
sudo ufw default deny incoming

# Allow SSH (port 22)
sudo ufw allow 22/tcp

# Allow HTTPS (port 443)
sudo ufw allow 443/tcp

# Allow HTTP (port 80)
sudo ufw allow 80/tcp

# Enable ufw
sudo ufw enable

# Reload ufw
sudo ufw reload

# Check ufw status
sudo ufw status
